version: '3.9'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: postgres

