version: '3.9'

services:
  postgres:
    image: postgres:16.0
    command: > 
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/server.crt
      -c ssl_key_file=/etc/ssl/private/server.key
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/data/db
      - ./certs/server.crt:/etc/ssl/certs/server.crt:ro
      - ./certs/server.key:/etc/ssl/private/server.key:ro
    container_name: postgres

